"""Ledger integrity: append-only enforcement, balance trigger, rebuild function.

This migration is what turns a set of tables into a trustworthy ledger
(ARCHITECTURE.md §6.4-6.5). Everything here is hand-written, never autogenerated.

  1. Unique index defining the balance grain.
  2. AFTER INSERT trigger maintaining stock_balances in the SAME transaction,
     so the projection can never drift from the ledger.
  3. BEFORE UPDATE/DELETE triggers that make stock_movements and audit_logs
     append-only. A trigger is used rather than REVOKE because the application
     connects as the table owner, and owners bypass grants.
  4. A trigger keeping stock_movements.tracking_mode in sync with the product.
  5. rebuild_balances() — recomputes the projection from the ledger. The CI test
     asserts this produces an identical result, which is the proof the system
     is sound.

Revision ID: b2000000
Revises: bf5a6bd4d92a
"""

from collections.abc import Sequence

from alembic import op

revision: str = "b2000000"
down_revision: str | None = "bf5a6bd4d92a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ---------------------------------------------------------------- grain
    # bin_id and lot_id are nullable, so a plain UNIQUE constraint would allow
    # duplicate rows (NULL != NULL). COALESCE makes the grain well-defined.
    op.execute("""
        CREATE UNIQUE INDEX ux_balance_grain ON stock_balances
          (product_id, warehouse_id, COALESCE(bin_id, 0), COALESCE(lot_id, 0), status);
    """)

    # ------------------------------------------------ append-only enforcement
    op.execute("""
        CREATE OR REPLACE FUNCTION reject_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION
                '% is append-only: % is not permitted. Post a reversing entry instead.',
                TG_TABLE_NAME, TG_OP
                USING ERRCODE = 'restrict_violation';
        END;
        $$ LANGUAGE plpgsql;
    """)

    for table in ("stock_movements", "audit_logs"):
        op.execute(f"""
            CREATE TRIGGER trg_{table}_append_only
            BEFORE UPDATE OR DELETE ON {table}
            FOR EACH ROW EXECUTE FUNCTION reject_mutation();
        """)

    # Belt and braces: also revoke, so a non-owner role cannot mutate either.
    op.execute("REVOKE UPDATE, DELETE ON stock_movements FROM PUBLIC;")
    op.execute("REVOKE UPDATE, DELETE ON audit_logs FROM PUBLIC;")

    # ------------------------------------- tracking_mode must match the product
    op.execute("""
        CREATE OR REPLACE FUNCTION sync_movement_tracking_mode() RETURNS trigger AS $$
        DECLARE
            product_mode tracking_mode;
        BEGIN
            SELECT tracking_mode INTO product_mode
            FROM products WHERE id = NEW.product_id;

            IF product_mode IS NULL THEN
                RAISE EXCEPTION 'product % does not exist', NEW.product_id;
            END IF;

            -- Authoritative: the product decides, the movement cannot disagree.
            NEW.tracking_mode := product_mode;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER trg_movement_tracking_mode
        BEFORE INSERT ON stock_movements
        FOR EACH ROW EXECUTE FUNCTION sync_movement_tracking_mode();
    """)

    # ------------------------------------------------ balance projection trigger
    # NOTE: deliberately NOT written as INSERT ... ON CONFLICT DO UPDATE.
    # Postgres evaluates CHECK constraints on the *proposed* row before resolving
    # the conflict, so an issue of -30 against a balance of 100 would propose a
    # row of -30 and trip chk_no_negative before the merge ever happened.
    #
    # Lock-then-check-then-write instead. The SELECT ... FOR UPDATE also
    # serialises concurrent movements on the same grain, which is exactly the
    # concurrency control described in ARCHITECTURE.md §6.7.
    op.execute("""
        CREATE OR REPLACE FUNCTION apply_movement_to_balance() RETURNS trigger AS $$
        DECLARE
            bal_id       BIGINT;
            current_qty  NUMERIC(18,4) := 0;
        BEGIN
            LOOP
                SELECT id, qty_on_hand INTO bal_id, current_qty
                FROM stock_balances
                WHERE product_id   = NEW.product_id
                  AND warehouse_id = NEW.warehouse_id
                  AND COALESCE(bin_id, 0) = COALESCE(NEW.bin_id, 0)
                  AND COALESCE(lot_id, 0) = COALESCE(NEW.lot_id, 0)
                  AND status = NEW.status
                FOR UPDATE;

                IF NOT FOUND THEN
                    bal_id := NULL;
                    current_qty := 0;
                END IF;

                IF current_qty + NEW.quantity < 0 THEN
                    RAISE EXCEPTION
                        'insufficient stock: product % at warehouse % has %, cannot move %',
                        NEW.product_id, NEW.warehouse_id, current_qty, NEW.quantity
                        USING ERRCODE = 'check_violation';
                END IF;

                IF bal_id IS NOT NULL THEN
                    UPDATE stock_balances
                    SET qty_on_hand = current_qty + NEW.quantity, updated_at = now()
                    WHERE id = bal_id;
                    RETURN NULL;
                END IF;

                -- No row yet. Try to create it; if another transaction beat us
                -- to it, loop and take the UPDATE path instead.
                BEGIN
                    INSERT INTO stock_balances (
                        product_id, warehouse_id, bin_id, lot_id, status,
                        qty_on_hand, qty_reserved, updated_at
                    )
                    VALUES (
                        NEW.product_id, NEW.warehouse_id, NEW.bin_id, NEW.lot_id,
                        NEW.status, NEW.quantity, 0, now()
                    );
                    RETURN NULL;
                EXCEPTION WHEN unique_violation THEN
                    -- fall through and retry
                END;
            END LOOP;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER trg_movement_to_balance
        AFTER INSERT ON stock_movements
        FOR EACH ROW EXECUTE FUNCTION apply_movement_to_balance();
    """)

    # ------------------------------------------------------------ rebuild proof
    op.execute("""
        CREATE OR REPLACE FUNCTION rebuild_balances() RETURNS void AS $$
        BEGIN
            DELETE FROM stock_balances;

            INSERT INTO stock_balances (
                product_id, warehouse_id, bin_id, lot_id, status,
                qty_on_hand, qty_reserved, updated_at
            )
            SELECT m.product_id, m.warehouse_id, m.bin_id, m.lot_id, m.status,
                   SUM(m.quantity), 0, now()
            FROM stock_movements m
            GROUP BY m.product_id, m.warehouse_id, m.bin_id, m.lot_id, m.status
            HAVING SUM(m.quantity) <> 0;

            -- Reservations live outside the ledger, so recompute them separately.
            UPDATE stock_balances b
            SET qty_reserved = COALESCE(r.total, 0)
            FROM (
                SELECT product_id, warehouse_id, lot_id, SUM(quantity) AS total
                FROM stock_reservations
                WHERE status = 'ACTIVE'
                GROUP BY product_id, warehouse_id, lot_id
            ) r
            WHERE b.product_id = r.product_id
              AND b.warehouse_id = r.warehouse_id
              AND COALESCE(b.lot_id, 0) = COALESCE(r.lot_id, 0)
              AND b.status = 'AVAILABLE';
        END;
        $$ LANGUAGE plpgsql;
    """)

    # ------------------------------------------------------------------- views
    op.execute("""
        CREATE VIEW v_stock_by_warehouse AS
        SELECT product_id, warehouse_id, status,
               SUM(qty_on_hand)  AS qty_on_hand,
               SUM(qty_reserved) AS qty_reserved,
               SUM(qty_on_hand) - SUM(qty_reserved) AS qty_available
        FROM stock_balances
        GROUP BY product_id, warehouse_id, status;
    """)

    # Convenience view for expiry alerting and FEFO inspection.
    op.execute("""
        CREATE VIEW v_expiring_stock AS
        SELECT b.product_id, p.sku, p.name AS product_name,
               b.warehouse_id, w.name AS warehouse_name,
               l.id AS lot_id, l.lot_code, l.expiry_date,
               b.qty_on_hand, b.status,
               (l.expiry_date - CURRENT_DATE) AS days_to_expiry
        FROM stock_balances b
        JOIN lots l       ON l.id = b.lot_id
        JOIN products p   ON p.id = b.product_id
        JOIN warehouses w ON w.id = b.warehouse_id
        WHERE b.qty_on_hand > 0 AND l.expiry_date IS NOT NULL;
    """)


def downgrade() -> None:
    op.execute("DROP VIEW IF EXISTS v_expiring_stock;")
    op.execute("DROP VIEW IF EXISTS v_stock_by_warehouse;")
    op.execute("DROP FUNCTION IF EXISTS rebuild_balances();")
    op.execute("DROP TRIGGER IF EXISTS trg_movement_to_balance ON stock_movements;")
    op.execute("DROP FUNCTION IF EXISTS apply_movement_to_balance();")
    op.execute("DROP TRIGGER IF EXISTS trg_movement_tracking_mode ON stock_movements;")
    op.execute("DROP FUNCTION IF EXISTS sync_movement_tracking_mode();")
    for table in ("stock_movements", "audit_logs"):
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_append_only ON {table};")
    op.execute("DROP FUNCTION IF EXISTS reject_mutation();")
    op.execute("DROP INDEX IF EXISTS ux_balance_grain;")
