"""Import every model so Alembic autogenerate and SQLAlchemy mappers see them."""

from app.models.documents import (
    DocumentSequence,
    GoodsReceipt,
    GoodsReceiptLine,
    PurchaseOrder,
    PurchaseOrderLine,
    Recall,
    SalesOrder,
    SalesOrderLine,
    Shipment,
    ShipmentLine,
    StockAdjustment,
    StockAdjustmentLine,
    StockTransfer,
    StockTransferLine,
)
from app.models.enums import (
    DemandArchetype,
    DocumentStatus,
    DrugSchedule,
    ForecastStatus,
    JobStatus,
    MovementType,
    RecallStatus,
    ReservationStatus,
    SerialStatus,
    StockStatus,
    StorageCondition,
    SuggestionStatus,
    TrackingMode,
)
from app.models.forecasting import (
    CalendarDay,
    Forecast,
    ForecastAccuracy,
    ForecastRun,
    ReorderSuggestion,
)
from app.models.identity import (
    AuditLog,
    Permission,
    RefreshToken,
    Role,
    RolePermission,
    User,
)
from app.models.jobs import Job
from app.models.masters import (
    Bin,
    Category,
    Customer,
    Product,
    ProductSupplier,
    Supplier,
    Uom,
    Warehouse,
)
from app.models.settings import FeatureFlag
from app.models.stock import (
    Lot,
    Serial,
    StockBalance,
    StockMovement,
    StockReservation,
)

__all__ = [
    "AuditLog",
    "Bin",
    "CalendarDay",
    "Category",
    "Customer",
    "DemandArchetype",
    "DocumentSequence",
    "DocumentStatus",
    "DrugSchedule",
    "FeatureFlag",
    "Forecast",
    "ForecastAccuracy",
    "ForecastRun",
    "ForecastStatus",
    "GoodsReceipt",
    "GoodsReceiptLine",
    "Job",
    "JobStatus",
    "Lot",
    "MovementType",
    "Permission",
    "Product",
    "ProductSupplier",
    "PurchaseOrder",
    "PurchaseOrderLine",
    "Recall",
    "RecallStatus",
    "RefreshToken",
    "ReorderSuggestion",
    "ReservationStatus",
    "Role",
    "RolePermission",
    "SalesOrder",
    "SalesOrderLine",
    "Serial",
    "SerialStatus",
    "Shipment",
    "ShipmentLine",
    "StockAdjustment",
    "StockAdjustmentLine",
    "StockBalance",
    "StockMovement",
    "StockReservation",
    "StockStatus",
    "StockTransfer",
    "StockTransferLine",
    "StorageCondition",
    "SuggestionStatus",
    "Supplier",
    "TrackingMode",
    "Uom",
    "User",
    "Warehouse",
]
